# Respective MANPATH entries would include /usr/local/share/man or $HOME/man.
INSTALLDIR=/usr/local/share/man/man1
INSTALLHOME=$(HOME)/man/man1

top: .always
	echo mkman start
	mkman.rb > mlr.1
	mkman.rb | groff -man -Tascii | col -b > manpage.txt
	echo mkman end

# These targets are only for local dev work.
install:
	mkdir -p $(INSTALLDIR)
	cp mlr.1 $(INSTALLDIR)/mlr.1
installhome:
	mkdir -p $(INSTALLHOME)
	cp mlr.1 $(INSTALLHOME)/mlr.1

.always:
	true
