echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length($x)'
echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length($y)'
echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length($nonesuch)'
echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length($*)'
echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length([])'
echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length([5,6,7])'
echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length({})'
echo "x=1,y=abcdefg,z=3" | run_mlr put '$n = length({"a":5,"b":6,"c":7})'
