run_mlr         --from $indir/s.dkvp put 'var x = 3'
run_mlr         --from $indir/s.dkvp put 'int x = 3'
run_mlr         --from $indir/s.dkvp put 'num x = 3'
mlr_expect_fail --from $indir/s.dkvp put 'str x = 3'
mlr_expect_fail --from $indir/s.dkvp put 'arr x = 3'

run_mlr         --from $indir/s.dkvp put 'func f(var x) { return 2*x} $y=f(3)'
run_mlr         --from $indir/s.dkvp put 'func f(int x) { return 2*x} $y=f(3)'
run_mlr         --from $indir/s.dkvp put 'func f(num x) { return 2*x} $y=f(3)'
mlr_expect_fail --from $indir/s.dkvp put 'func f(str x) { return 2*x} $y=f(3)'
mlr_expect_fail --from $indir/s.dkvp put 'func f(arr x) { return 2*x} $y=f(3)'

run_mlr         --from $indir/s.dkvp put 'func f(x): var { return 2*x} $y=f(3)'
run_mlr         --from $indir/s.dkvp put 'func f(x): int { return 2*x} $y=f(3)'
run_mlr         --from $indir/s.dkvp put 'func f(x): num { return 2*x} $y=f(3)'
mlr_expect_fail --from $indir/s.dkvp put 'func f(x): str { return 2*x} $y=f(3)'
mlr_expect_fail --from $indir/s.dkvp put 'func f(x): arr { return 2*x} $y=f(3)'
