run_mlr --from $indir/s.dkvp put 'if (NR == 1) { $z = 100 }'
run_mlr --from $indir/s.dkvp put 'if (NR == 1) { $z = 100 } else { $z = 900 }'
run_mlr --from $indir/s.dkvp put 'if (NR == 1) { $z = 100 } elif (NR == 2) { $z = 200 }'
run_mlr --from $indir/s.dkvp put 'if (NR == 1) { $z = 100 } elif (NR == 2) { $z = 200 } else { $z = 900 }'
run_mlr --from $indir/s.dkvp put 'if (NR == 1) { $z = 100 } elif (NR == 2) { $z = 200 } elif (NR == 3) { $z = 300 } else { $z = 900 }'
