# .goreleaser.yml
release:
  github:
    owner: johnkerl
    name: miller

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

#gomod:
#  proxy: true

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - aix
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
      - ppc64
      - riscv64
    goarm:
      - 6
      - 7
    ignore:
      - goos: linux
        goarch: ppc64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: s390x
    dir: .
    main: ./cmd/mlr
    binary: mlr
    flags:
      - -trimpath
    #ldflags:
    #  - -s -w 

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE.txt
      - README.md

nfpms:
  -
    id: miller-nfpms
    package_name: miller
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/johnkerl/miller
    maintainer: "John Kerl <johnkerl@users.noreply.github.com>"
    description: Miller is like awk, sed, cut, join, and sort for data formats such as CSV, TSV, tabular JSON etc
    license: BSD
    formats:
      - deb
      - rpm

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
