#!/bin/bash
set -euo pipefail

if [ $# -ge 1 ]; then
  for name; do
    if [[ $name == *.md.in ]]; then
      genmds $name;
    fi
  done
else
  for rstin in *.md.in; do genmds $rstin; done
fi
sphinx-build -M html . _build
