#!/usr/bin/env ruby

while true
	begin
		line = $stdin.readline.chomp
	rescue EOFError
		break
	end

  if line =~ /GENMD_RUN_COMMAND{{.*}}HERE/
    line.sub!("GENMD_RUN_COMMAND{{", "")
    line.sub!("}}HERE", "")
    puts 'GENMD_RUN_COMMAND'
    puts line
    puts 'GENMD_EOF'
  else
    puts line
  end
end
