#!/bin/bash

# See ./reg-test/run
diff_context_flag=""
for arg; do
  if [ "$arg" = "-C5" ]; then
    diff_context_flag="$arg"
  else
    for suffix in out err; do
      expfile=./reg-test/expected/$arg.$suffix
      outfile=./output-reg-test/$arg.$suffix
      diff -a -I '^mlr' -I '^Miller:' -I '^cat' $expfile $outfile
    done
  fi
done
