#!/bin/bash

path_to_mlr="./mlr"
indir="./regtest/input"

#go build mlr.go
if [ $? -ne 0 ]; then
  exit 1
fi

# ----------------------------------------------------------------
run_mlr() {
  echo
  echo ---------------------------------------------------------------- "$@"
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
}

# ----------------------------------------------------------------
mlr_expect_fail() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
  status=$?
  if [ $status -eq 0 ]; then
    echo "failed to fail"
  fi
}

# ----------------------------------------------------------------
run_cat() {
  echo
  echo cat "$@"
  echo
  cat "$@"
}

# ----------------------------------------------------------------
announce() {
  echo
  echo "================================================================"
  echo
  echo "$@"
}

# ----------------------------------------------------------------
mention() {
  echo
  echo ---------------------------------------------------------------- "$@"
}

# ================================================================

mlr --c2p cat regtest/input/merge-fields-in-out.csv
echo
../c/mlr --csvlite --opprint merge-fields    -a p0,min,p29,max,p100,sum -c _in,_out regtest/input/merge-fields-in-out.csv
echo
../go/mlr --csvlite --opprint merge-fields    -a p0,min,p29,max,p100,sum -c _in,_out regtest/input/merge-fields-in-out.csv

# ================================================================
