#!/bin/bash

path_to_mlr="./mlr"
indir="./regtest/input"

#go build mlr.go
if [ $? -ne 0 ]; then
  exit 1
fi

# ----------------------------------------------------------------
run_mlr() {
  echo
  echo ---------------------------------------------------------------- "$@"
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
}

# ----------------------------------------------------------------
mlr_expect_fail() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
  status=$?
  if [ $status -eq 0 ]; then
    echo "failed to fail"
  fi
}

# ----------------------------------------------------------------
run_cat() {
  echo
  echo cat "$@"
  echo
  cat "$@"
}

# ----------------------------------------------------------------
announce() {
  echo
  echo "================================================================"
  echo
  echo "$@"
}

# ----------------------------------------------------------------
mention() {
  echo
  echo ---------------------------------------------------------------- "$@"
}

# ================================================================

run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f x,y -b u
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f u,v -b x
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f z,w,s -b v
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f u,v -b nonesuch
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f u,nonesuch -b x

run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f x,y -a u
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f u,v -a x
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f z,w,s -a v
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f u,v -a nonesuch
run_mlr --from ../go/regtest/input/reorder.dkvp reorder -f u,nonesuch -a x

# ================================================================
