#!/bin/bash

path_to_mlr="./mlr"
indir="./regtest/input"

go build mlr.go
if [ $? -ne 0 ]; then
  exit 1
fi

# ----------------------------------------------------------------
run_mlr() {
  echo
  echo ---------------------------------------------------------------- "$@"
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
}

# ----------------------------------------------------------------
mlr_expect_fail() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
  status=$?
  if [ $status -eq 0 ]; then
    echo "failed to fail"
  fi
}

# ----------------------------------------------------------------
run_cat() {
  echo
  echo cat "$@"
  echo
  cat "$@"
}

# ----------------------------------------------------------------
announce() {
  echo
  echo "================================================================"
  echo
  echo "$@"
}

# ----------------------------------------------------------------
mention() {
  echo
  echo ---------------------------------------------------------------- "$@"
}

# ================================================================

echo 'x=a;b;c'                         | run_mlr nest -evF -f x
echo 'foo=bar,x=a;b;c'                 | run_mlr nest -evF -f x
echo 'x=a;b;c,foo=bar'                 | run_mlr nest -evF -f x

echo 'x=a;b;c'                         | run_mlr nest -evR -f x
echo 'foo=bar,x=a;b;c'                 | run_mlr nest -evR -f x
echo 'x=a;b;c,foo=bar'                 | run_mlr nest -evR -f x

echo 'x=a|b|c'                         | run_mlr nest -evF -S pipe -f x
echo 'foo=bar,x=a|b|c'                 | run_mlr nest -evF -S pipe -f x
echo 'x=a|b|c,foo=bar'                 | run_mlr nest -evF -S pipe -f x

echo 'x=a|b|c'                         | run_mlr nest -evF -S '|' -f x
echo 'foo=bar,x=a|b|c'                 | run_mlr nest -evF -S '|' -f x
echo 'x=a|b|c,foo=bar'                 | run_mlr nest -evF -S '|' -f x

echo 'x=a;b;c'                         | run_mlr nest -evR -f x
echo 'foo=bar,x=a;b;c'                 | run_mlr nest -evR -f x
echo 'x=a;b;c,foo=bar'                 | run_mlr nest -evR -f x


echo 'x=a:1;b:2;c:3'                   | run_mlr nest -epF -f x
echo 'foo=bar,x=a:1;b:2;c:3'           | run_mlr nest -epF -f x
echo 'x=a:1;b:2;c:3,foo=bar'           | run_mlr nest -epF -f x

echo 'x=a:1;b:2;c:3'                   | run_mlr nest -epR -f x
echo 'foo=bar,x=a:1;b:2;c:3'           | run_mlr nest -epR -f x
echo 'x=a:1;b:2;c:3,foo=bar'           | run_mlr nest -epR -f x

echo 'x_1=a:1,x_2=b:2,x_3=c:3'         | run_mlr nest -ivF -f x
echo 'foo=bar,x_1=a:1,x_2=b:2,x_3=c:3' | run_mlr nest -ivF -f x
echo 'x_1=a:1,x_2=b:2,x_3=c:3,foo=bar' | run_mlr nest -ivF -f x

# ================================================================
