#!/bin/bash

set -euo pipefail

echo; mlr -n put -v '$y = 1 || 2'
echo; mlr -n put -v '$y = 1 || 2 || 3'
echo; mlr -n put -v '$y = 1 || 2 && 3'
echo; mlr -n put -v '$y = 1 && 2 || 3'
echo; mlr -n put -v '$y = 1 ? 2 : 3'
echo; mlr -n put -v '$y = $a + $b * $c'
echo; mlr -n put -v '$y = $a * $b * $c'
echo; mlr -n put -v '$y = $a ** $b ** $c'
echo; mlr -n put -v '$[2] = 3'
echo; mlr -n put -v '$[$y] = 4'
#echo; mlr -n put -v '${1} = 4'
echo; mlr -n put -v '$x = "abc"'
echo; mlr -n put -v '$["abc"] = "def"'
echo; mlr -n put -v '$[FILENAME] = FNR'
echo; mlr -n put -v '$x = $a + $b + $c'
echo; mlr -n put -v '$x = ($a + $b) + $c; $y = $a + ($b + $c); $z = $a + ($b)+ $c'
echo; mlr -n put -v '$x = 2 * $a + $b . $c'
echo; mlr -n put -v '$x = 2 * $a + ($b . $c)'
echo; mlr -n put -v '$x = (NF + NR) * 7; $y = OFS . $y . "hello"'
echo; mlr -n put -v '$x = 123. + 1e-2 / .2e3 + 1.e-3'
