#!/usr/bin/env ruby 

dirname=ARGV.shift
ARGV.each do |cmd_file_name|
  mlr_file_name = cmd_file_name.sub(/\.cmd$/, '.mlr')
  cmd_file_contents = File.read(cmd_file_name)
  cmd_file_contents.match(/(.*)'(.*)'(.*)/)
  left   = $1
  middle = $2
  right  = $3
  File.write(mlr_file_name, middle.strip + "\n")
  File.write(cmd_file_name, "#{left}-f #{dirname}/#{mlr_file_name}#{right}".strip + "\n")
  $stdout.puts mlr_file_name
end
