#!/bin/bash

# ================================================================
# GO-SOURCE TESTS
# Note reg-test/run has FAR more test cases
# ================================================================

# go test -v ./... doesn't work since it triggers unready things in
# src/github.com/goccmack

go test miller/src/types
go test src/dsl/ast_test.go
