#!/bin/bash

set -euo pipefail

run_mlr() {
  # Use just "mlr" for info messages
  echo
  echo ----------------------------------------------------------------
  echo mlr "$@"
  ./mlr "$@"
}

ofmt=pprint
for ifmt in csv dkvp nidx json; do
  echo ---------------------------------------------------------------- $ifmt $ofmt
  run_mlr --i$ifmt --o$ofmt put '
    $nf=NF;
    $nr=NR;
    $fnr=FNR;
    $filename=FILENAME;
    $filenum=FILENUM;
  ' u/s.$ifmt u/t.$ifmt
  echo
done

echo
echo
echo

ifmt=dkvp
for ofmt in pprint csv dkvp nidx json; do
  echo ---------------------------------------------------------------- $ifmt $ofmt
  run_mlr --i$ifmt --o$ofmt put '
    $nf=NF;
    $nr=NR;
    $fnr=FNR;
    $filename=FILENAME;
    $filenum=FILENUM;
  ' u/s.$ifmt u/t.$ifmt
  echo
done

echo
echo
echo
run_mlr --ocsv    cat u/het.dkvp
run_mlr --opprint cat u/het.dkvp

run_mlr --opprint cat << EOF
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
a=2,b=2,c=3
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
a=2,b=2,c=3
d=3,e=5,f=6
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
d=2,e=5,f=6
d=3,e=5,f=6
EOF

run_mlr --opprint --barred cat u/s.dkvp
run_mlr --opprint --barred cat u/het.dkvp

# To-do: port format-specific default separators from C.
# E.g. NIDX's IFS should default to space.
echo 'a,b,c,d,e,f' | run_mlr --inidx --oxtab cat
echo 'a b c d e f' | run_mlr --inidx --oxtab cat

echo 'a,b,c,d,e,f' | run_mlr --inidx --ifs , --oxtab cat
echo 'a b c d e f' | run_mlr --inidx --ifs , --oxtab cat
echo 'a,b,c,d,e,f' | run_mlr --inidx --ifs ' ' --oxtab cat
echo 'a b c d e f' | run_mlr --inidx --ifs ' ' --oxtab cat

echo 'a,b,c,d,e,f' | run_mlr --inidx --ifs comma --oxtab cat
echo 'a b c d e f' | run_mlr --inidx --ifs comma --oxtab cat
echo 'a,b,c,d,e,f' | run_mlr --inidx --ifs space --oxtab cat
echo 'a b c d e f' | run_mlr --inidx --ifs space --oxtab cat

run_mlr --itsv --ocsv cat u/s.tsv
run_mlr --icsv --otsv cat u/s.tsv
run_mlr --icsv --otsv cat u/s.csv
run_mlr --c2j cat u/s.csv

run_mlr --ocsv cat u/het.dkvp
run_mlr --ocsv --headerless-csv-output cat u/het.dkvp
run_mlr --icsv --ojson cat u/implicit.csv
run_mlr --implicit-csv-header --icsv --ojson cat u/implicit.csv
