#!/bin/bash

set -euo pipefail

run_mlr() {
  # Use just "mlr" for info messages
  echo
  echo ----------------------------------------------------------------
  echo mlr "$@"
  ./mlr "$@"
}

run_mlr --opprint cat           u/s.dkvp
run_mlr --opprint cat -n        u/s.dkvp
run_mlr --opprint cat -n -g a   u/s.dkvp
run_mlr --opprint cat -n -g a,b u/s.dkvp

run_mlr --opprint cut    -f x,a u/s.dkvp
run_mlr --opprint cut -o -f x,a u/s.dkvp
run_mlr --opprint cut -x -f x,a u/s.dkvp


run_mlr --opprint head -n 1 u/s.dkvp
run_mlr --opprint head -n 1 -g a u/s.dkvp
run_mlr --opprint head -n 1 -g a,b u/s.dkvp

run_mlr --opprint tail -n 1 u/medium.dkvp
run_mlr --opprint tail -n 1 -g a u/medium.dkvp
run_mlr --opprint tail -n 1 -g a,b u/medium.dkvp

run_mlr --opprint group-like u/het.dkvp
run_mlr --opprint group-by a u/medium.dkvp
run_mlr --opprint group-by a,b u/medium.dkvp

run_mlr --opprint rename a,AAA u/s.dkvp
run_mlr --opprint rename a,AAA,x,XXX u/s.dkvp
run_mlr --opprint rename none,such u/s.dkvp
run_mlr --opprint rename a,b u/s.dkvp
run_mlr --opprint rename i,j,a,b u/s.dkvp
run_mlr --opprint rename x,y,a,b u/s.dkvp

run_mlr --opprint label A,B,I u/s.dkvp
run_mlr --opprint label A,B,I,X,Y u/s.dkvp
run_mlr --opprint label A,B,I,X,Y,Z u/s.dkvp
run_mlr --opprint label b,i,x u/s.dkvp
run_mlr --opprint label x,i,b u/s.dkvp

run_mlr --opprint --from u/s.dkvp sort -f nonesuch
run_mlr --opprint --from u/s.dkvp sort -f a
run_mlr --opprint --from u/s.dkvp sort -f a,b
run_mlr --opprint --from u/s.dkvp sort -r a
run_mlr --opprint --from u/s.dkvp sort -r a,b
run_mlr --opprint --from u/s.dkvp sort -f a -r b
run_mlr --opprint --from u/s.dkvp sort -f b -n i
run_mlr --opprint --from u/s.dkvp sort -f b -nr i

run_mlr --json --from u/needs-sorting.json sort-within-records
run_mlr --json --from u/needs-regularize.json regularize
run_mlr --opprint --from u/needs-unsparsify.dkvp unsparsify
run_mlr --opprint --from u/needs-unsparsify.dkvp unsparsify --fill-with X

run_mlr --opprint --from u/medium.dkvp count
run_mlr --opprint --from u/medium.dkvp count -g a
run_mlr --opprint --from u/medium.dkvp count -g a,b
run_mlr --opprint --from u/medium.dkvp count -g a -n
run_mlr --opprint --from u/medium.dkvp count -g a,b -n
run_mlr --opprint --from u/medium.dkvp count -o NAME
run_mlr --opprint --from u/medium.dkvp count -g a -o NAME

run_mlr --opprint --from u/s.dkvp grep pan
run_mlr --opprint --from u/s.dkvp grep -v pan
run_mlr --opprint --from u/s.dkvp grep PAN
run_mlr --opprint --from u/s.dkvp grep -i PAN
run_mlr --opprint --from u/s.dkvp grep -i -v PAN

run_mlr --from u/s.dkvp skip-trivial-records
run_mlr --from u/skip-trivial-records.dkvp skip-trivial-records

echo 'a,b,c,d,e,f'   | run_mlr --inidx --ifs comma altkv
echo 'a,b,c,d,e,f,g' | run_mlr --inidx --ifs comma altkv

run_mlr --from u/s.csv                    --icsv --opprint remove-empty-columns
run_mlr --from u/remove-empty-columns.csv --icsv --opprint cat
run_mlr --from u/remove-empty-columns.csv --icsv --opprint remove-empty-columns

run_mlr --icsv --opprint fill-down -f z       u/remove-empty-columns.csv
run_mlr --icsv --opprint fill-down -f a,b,c,d u/remove-empty-columns.csv

run_mlr --icsv --opprint reorder -f x,i    u/s.dkvp
run_mlr --icsv --opprint reorder -f x,i -e u/s.dkvp

run_mlr decimate       -n 2 u/s.dkvp
run_mlr decimate -b    -n 2 u/s.dkvp
run_mlr decimate    -e -n 2 u/s.dkvp
run_mlr decimate -b -e -n 2 u/s.dkvp
