#!/bin/bash

set -euo pipefail

run_mlr() {
  # Use just "mlr" for info messages
  echo
  echo ----------------------------------------------------------------
  echo mlr "$@"
  mlr "$@"
}

ofmt=pprint
for ifmt in csv dkvp nidx json; do
  echo ---------------------------------------------------------------- $ifmt $ofmt
  run_mlr --i$ifmt --o$ofmt put '
    $nf=NF;
    $nr=NR;
    $fnr=FNR;
    $filename=FILENAME;
    $filenum=FILENUM;
  ' u/s.$ifmt u/t.$ifmt
  echo
done

echo
echo
echo

ifmt=dkvp
for ofmt in pprint csv dkvp nidx json; do
  echo ---------------------------------------------------------------- $ifmt $ofmt
  run_mlr --i$ifmt --o$ofmt put '
    $nf=NF;
    $nr=NR;
    $fnr=FNR;
    $filename=FILENAME;
    $filenum=FILENUM;
  ' u/s.$ifmt u/t.$ifmt
  echo
done
