#!/bin/bash

n=10

repeat $n justtime mlr cat ../data/nmc1.dkvp > /dev/null
echo
repeat $n justtime mlr --csv cat ../data/nmc1.csv > /dev/null
echo
repeat $n justtime mlr --csv cut -x -f ccode,version ../data/nmc1.csv > /dev/null
echo
echo
repeat $n justtime ../c/mlr cat ../data/nmc1.dkvp > /dev/null
echo
repeat $n justtime ../c/mlr --csv cat ../data/nmc1.csv > /dev/null
echo
repeat $n justtime ../c/mlr --csv cut -x -f ccode,version ../data/nmc1.csv > /dev/null

