#!/bin/bash

set -euo pipefail

run_mlr() {
  # Use just "mlr" for info messages
  echo
  echo ----------------------------------------------------------------
  echo mlr "$@"
  mlr "$@"
}

ofmt=pprint
for ifmt in csv dkvp nidx json; do
  echo ---------------------------------------------------------------- $ifmt $ofmt
  run_mlr --i$ifmt --o$ofmt put '
    $nf=NF;
    $nr=NR;
    $fnr=FNR;
    $filename=FILENAME;
    $filenum=FILENUM;
  ' u/s.$ifmt u/t.$ifmt
  echo
done

echo
echo
echo

ifmt=dkvp
for ofmt in pprint csv dkvp nidx json; do
  echo ---------------------------------------------------------------- $ifmt $ofmt
  run_mlr --i$ifmt --o$ofmt put '
    $nf=NF;
    $nr=NR;
    $fnr=FNR;
    $filename=FILENAME;
    $filenum=FILENUM;
  ' u/s.$ifmt u/t.$ifmt
  echo
done

echo
echo
echo
run_mlr --ocsv    cat u/het.dkvp
run_mlr --opprint cat u/het.dkvp

run_mlr --opprint cat << EOF
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
a=2,b=2,c=3
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
a=2,b=2,c=3
d=3,e=5,f=6
EOF

run_mlr --opprint cat << EOF
a=1,b=2,c=3
d=2,e=5,f=6
d=3,e=5,f=6
EOF


