#!/bin/bash

set -euo pipefail

run_mlr() {
  # Use just "mlr" for info messages
  echo
  echo ----------------------------------------------------------------
  echo mlr "$@"
  mlr "$@"
}

run_mlr --opprint cut    -f x,a u/s.dkvp
run_mlr --opprint cut -o -f x,a u/s.dkvp
run_mlr --opprint cut -x -f x,a u/s.dkvp


run_mlr --opprint head -n 1 u/s.dkvp
run_mlr --opprint head -n 1 -g a u/s.dkvp
run_mlr --opprint head -n 1 -g a,b u/s.dkvp

run_mlr --opprint tail -n 1 u/medium.dkvp
run_mlr --opprint tail -n 1 -g a u/medium.dkvp
run_mlr --opprint tail -n 1 -g a,b u/medium.dkvp

run_mlr --opprint group-like u/het.dkvp
run_mlr --opprint group-by a u/medium.dkvp
run_mlr --opprint group-by a,b u/medium.dkvp

run_mlr --opprint rename a,AAA u/s.dkvp
run_mlr --opprint rename a,AAA,x,XXX u/s.dkvp
run_mlr --opprint rename none,such u/s.dkvp
run_mlr --opprint rename a,b u/s.dkvp
run_mlr --opprint rename i,j,a,b u/s.dkvp
run_mlr --opprint rename x,y,a,b u/s.dkvp

run_mlr --opprint label A,B,I u/s.dkvp
run_mlr --opprint label A,B,I,X,Y u/s.dkvp
run_mlr --opprint label A,B,I,X,Y,Z u/s.dkvp
run_mlr --opprint label b,i,x u/s.dkvp
run_mlr --opprint label x,i,b u/s.dkvp
