#!/bin/bash

# ================================================================
# tempware for converting regtest-v1 data to regtest-v2
# ================================================================

#set -euo pipefail

mlr="mlr"
newcasesdir="./reg-test/cases"
if [ $# -ge 1 -a "$1" = "-c" ]; then
  mlr="../c/mlr"
  newcasesdir="./reg-test/cases-pending-go-port"
  shift
elif [ $# -ge 1 -a "$1" = "-w" ]; then
  newcasesdir="./reg-test/cases-pending-windows"
  shift
fi

if [ $# -ne 1 ]; then
  echo "Usage: $0 {case-name}" 1>&2
  exit 1
fi
name="$1"

oldfile="./reg-test/cases/case-${name}.sh"
if [ ! -f "$oldfile" ]; then
  echo "Not found: $oldfile" 1>&2
  exit 1
fi

newdir="$newcasesdir/$name"
mkdir -p $newdir

u/upp $newdir < $oldfile

mlr regtest -m $mlr -p $newdir
mlr regtest -m $mlr -vv $newdir
git rm -f $oldfile
echo git rm ./reg-test/expected/case-${name}.sh.out
echo git rm ./reg-test/expected/case-${name}.sh.err
git rm -f ./reg-test/expected/case-${name}.sh.out
git rm -f ./reg-test/expected/case-${name}.sh.err
git add $newdir/*
