#!/bin/bash


export     CCOPT="clang -fsanitize=address -std=gnu99 -I. -I.. -Wall -Werror -O3 -lm"
export   CCDEBUG="clang -fsanitize=address -std=gnu99 -I. -I.. -Wall -Werror -g  -lm"

export     DSLCC="clang"
export DSLCFLAGS="-I.. -Wall -O2 -fsanitize=address"

make -e -f Makefile.no-autoconfig -C dsls clean
make -e -f Makefile.no-autoconfig mlr mlrg
