#!/bin/bash


export     CCOPT="clang -std=gnu99 -I. -I.. -Wall -Werror -O3 -lm"
export   CCDEBUG="clang -std=gnu99 -I. -I.. -Wall -Werror -g  -lm"

export     DSLCC="clang"
#export DSLCFLAGS="-I.. -Wall -O2"
export DSLCFLAGS="-I.. -Wall -O2 -g"

make -e -f Makefile.no-autoconfig -C parsing clean
make -e -f Makefile.no-autoconfig mlr mlrg
