#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 {case name}" 1>&2
  exit 1
fi
name="$1"
shift

sh=reg_test/case-${name}.sh
if [ -f "$sh" ]; then
    echo "Case file $sh already exists" 1>&2
    exit 1
fi
cat "$@" | uind -s > $sh
