// ================================================================
// Tests mlrval constructors.
// ================================================================

package mlrval

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestInferWithOctalAsString(t *testing.T) {
	assert.True(t, inferWithOctalAsString(FromDeferredType(""), false).IsVoid())

	assert.True(t, inferWithOctalAsString(FromDeferredType("true"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("false"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("true"), true).IsBool())
	assert.True(t, inferWithOctalAsString(FromDeferredType("false"), true).IsBool())

	assert.True(t, inferWithOctalAsString(FromDeferredType("abc"), false).IsString())

	assert.True(t, inferWithOctalAsString(FromDeferredType("0123"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-0123"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0377"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-0377"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0923"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-0923"), false).IsString())

	assert.True(t, inferWithOctalAsString(FromDeferredType("123"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-123"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0xff"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-0xff"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0b1011"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-0b1011"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0x7fffffffffffffff"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0x8000000000000000"), false).IsInt())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0xffffffffffffffff"), false).IsInt())

	assert.True(t, inferWithOctalAsString(FromDeferredType("12_3"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-12_3"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("1_2.3_4"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-1_2.3_4"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0xca_fe"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-0xca_fe"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("0b1011_1101"), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-0b1011_1101"), false).IsString())

	assert.True(t, inferWithOctalAsString(FromDeferredType("."), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-."), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("123."), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-123."), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType(".123"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-.123"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("123.456"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-123.456"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("1e2."), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-1e2."), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("1e-2."), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-1e-2."), false).IsString())
	assert.True(t, inferWithOctalAsString(FromDeferredType("1.2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-1.2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("1.2e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-1.2e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("1.e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-1.e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("1.e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-1.e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType(".2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-.2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType(".2e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsString(FromDeferredType("-.2e-3"), false).IsFloat())
}

func TestInferWithOctalAsInt(t *testing.T) {
	assert.True(t, inferWithOctalAsInt(FromDeferredType(""), false).IsVoid())

	assert.True(t, inferWithOctalAsInt(FromDeferredType("true"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("false"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("true"), true).IsBool())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("false"), true).IsBool())

	assert.True(t, inferWithOctalAsInt(FromDeferredType("abc"), false).IsString())

	assert.True(t, inferWithOctalAsInt(FromDeferredType("0123"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-0123"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0377"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-0377"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0923"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-0923"), false).IsFloat())

	assert.True(t, inferWithOctalAsInt(FromDeferredType("123"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-123"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0xff"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-0xff"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0b1011"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-0b1011"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0x7fffffffffffffff"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0x8000000000000000"), false).IsInt())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0xffffffffffffffff"), false).IsInt())

	assert.True(t, inferWithOctalAsInt(FromDeferredType("12_3"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-12_3"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("1_2.3_4"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-1_2.3_4"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0xca_fe"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-0xca_fe"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("0b1011_1101"), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-0b1011_1101"), false).IsString())

	assert.True(t, inferWithOctalAsInt(FromDeferredType("."), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-."), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("123."), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-123."), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType(".123"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-.123"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("123.456"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-123.456"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("1e2."), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-1e2."), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("1e-2."), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-1e-2."), false).IsString())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("1.2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-1.2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("1.2e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-1.2e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("1.e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-1.e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("1.e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-1.e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType(".2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-.2e3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType(".2e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-.2e-3"), false).IsFloat())
}

func TestInferWithIntAsFloat(t *testing.T) {
	assert.True(t, inferWithIntAsFloat(FromDeferredType(""), false).IsVoid())

	assert.True(t, inferWithIntAsFloat(FromDeferredType("true"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("false"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("true"), true).IsBool())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("false"), true).IsBool())

	assert.True(t, inferWithIntAsFloat(FromDeferredType("abc"), false).IsString())

	assert.True(t, inferWithIntAsFloat(FromDeferredType("0123"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-0123"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0377"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-0377"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0923"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-0923"), false).IsString())

	assert.True(t, inferWithIntAsFloat(FromDeferredType("123"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-123"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0xff"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-0xff"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0b1011"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-0b1011"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0x7fffffffffffffff"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0x8000000000000000"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0xffffffffffffffff"), false).IsFloat())

	assert.True(t, inferWithIntAsFloat(FromDeferredType("12_3"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-12_3"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("1_2.3_4"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-1_2.3_4"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0xca_fe"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-0xca_fe"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("0b1011_1101"), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-0b1011_1101"), false).IsString())

	assert.True(t, inferWithIntAsFloat(FromDeferredType("."), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-."), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("123."), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-123."), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType(".123"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-.123"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("123.456"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-123.456"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("1e2."), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-1e2."), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("1e-2."), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-1e-2."), false).IsString())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("1.2e3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-1.2e3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("1.2e-3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-1.2e-3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("1.e3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-1.e3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("1.e-3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-1.e-3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType(".2e3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType("-.2e3"), false).IsFloat())
	assert.True(t, inferWithIntAsFloat(FromDeferredType(".2e-3"), false).IsFloat())
	assert.True(t, inferWithOctalAsInt(FromDeferredType("-.2e-3"), false).IsFloat())
}

func TestInferStringOnly(t *testing.T) {
	assert.True(t, inferStringOnly(FromDeferredType(""), false).IsVoid())

	assert.True(t, inferStringOnly(FromDeferredType("true"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("false"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("true"), true).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("false"), true).IsString())

	assert.True(t, inferStringOnly(FromDeferredType("abc"), false).IsString())

	assert.True(t, inferStringOnly(FromDeferredType("0123"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-0123"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0377"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-0377"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0923"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-0923"), false).IsString())

	assert.True(t, inferStringOnly(FromDeferredType("123"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-123"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0xff"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-0xff"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0b1011"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-0b1011"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0x7fffffffffffffff"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0x8000000000000000"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0xffffffffffffffff"), false).IsString())

	assert.True(t, inferStringOnly(FromDeferredType("12_3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-12_3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("1_2.3_4"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-1_2.3_4"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0xca_fe"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-0xca_fe"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("0b1011_1101"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-0b1011_1101"), false).IsString())

	assert.True(t, inferStringOnly(FromDeferredType("."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("123."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-123."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType(".123"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-.123"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("123.456"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-123.456"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("1e2."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-1e2."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("1e-2."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-1e-2."), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("1.2e3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-1.2e3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("1.2e-3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-1.2e-3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("1.e3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-1.e3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("1.e-3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-1.e-3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType(".2e3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-.2e3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType(".2e-3"), false).IsString())
	assert.True(t, inferStringOnly(FromDeferredType("-.2e-3"), false).IsString())
}
