// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 36: // ['$','$']
			return 4
		case r == 37: // ['%','%']
			return 5
		case r == 38: // ['&','&']
			return 6
		case r == 40: // ['(','(']
			return 7
		case r == 41: // [')',')']
			return 8
		case r == 42: // ['*','*']
			return 9
		case r == 43: // ['+','+']
			return 10
		case r == 44: // [',',',']
			return 11
		case r == 45: // ['-','-']
			return 12
		case r == 46: // ['.','.']
			return 13
		case r == 47: // ['/','/']
			return 14
		case r == 48: // ['0','0']
			return 15
		case 49 <= r && r <= 57: // ['1','9']
			return 16
		case r == 58: // [':',':']
			return 17
		case r == 59: // [';',';']
			return 18
		case r == 60: // ['<','<']
			return 19
		case r == 61: // ['=','=']
			return 20
		case r == 62: // ['>','>']
			return 21
		case r == 63: // ['?','?']
			return 22
		case r == 64: // ['@','@']
			return 23
		case 65 <= r && r <= 69: // ['A','E']
			return 24
		case r == 70: // ['F','F']
			return 25
		case 71 <= r && r <= 72: // ['G','H']
			return 24
		case r == 73: // ['I','I']
			return 26
		case 74 <= r && r <= 76: // ['J','L']
			return 24
		case r == 77: // ['M','M']
			return 27
		case r == 78: // ['N','N']
			return 28
		case r == 79: // ['O','O']
			return 29
		case 80 <= r && r <= 90: // ['P','Z']
			return 24
		case r == 91: // ['[','[']
			return 30
		case r == 93: // [']',']']
			return 31
		case r == 94: // ['^','^']
			return 32
		case r == 95: // ['_','_']
			return 33
		case r == 97: // ['a','a']
			return 24
		case r == 98: // ['b','b']
			return 34
		case 99 <= r && r <= 100: // ['c','d']
			return 24
		case r == 101: // ['e','e']
			return 35
		case r == 102: // ['f','f']
			return 36
		case 103 <= r && r <= 104: // ['g','h']
			return 24
		case r == 105: // ['i','i']
			return 37
		case 106 <= r && r <= 115: // ['j','s']
			return 24
		case r == 116: // ['t','t']
			return 38
		case 117 <= r && r <= 122: // ['u','z']
			return 24
		case r == 123: // ['{','{']
			return 39
		case r == 124: // ['|','|']
			return 40
		case r == 125: // ['}','}']
			return 41
		case r == 126: // ['~','~']
			return 42
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 43
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 44
		case r == 33: // ['!','!']
			return 44
		case r == 34: // ['"','"']
			return 45
		case r == 35: // ['#','#']
			return 44
		case r == 36: // ['$','$']
			return 44
		case r == 37: // ['%','%']
			return 44
		case r == 38: // ['&','&']
			return 44
		case r == 39: // [''',''']
			return 44
		case r == 40: // ['(','(']
			return 44
		case r == 41: // [')',')']
			return 44
		case r == 42: // ['*','*']
			return 44
		case r == 43: // ['+','+']
			return 44
		case r == 44: // [',',',']
			return 44
		case r == 45: // ['-','-']
			return 44
		case r == 46: // ['.','.']
			return 44
		case r == 47: // ['/','/']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 44
		case r == 58: // [':',':']
			return 44
		case r == 59: // [';',';']
			return 44
		case r == 60: // ['<','<']
			return 44
		case r == 61: // ['=','=']
			return 44
		case r == 62: // ['>','>']
			return 44
		case r == 63: // ['?','?']
			return 44
		case r == 64: // ['@','@']
			return 44
		case 65 <= r && r <= 90: // ['A','Z']
			return 44
		case r == 91: // ['[','[']
			return 44
		case r == 92: // ['\','\']
			return 46
		case r == 93: // [']',']']
			return 44
		case r == 94: // ['^','^']
			return 44
		case r == 95: // ['_','_']
			return 44
		case r == 96: // ['`','`']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		case r == 123: // ['{','{']
			return 44
		case r == 124: // ['|','|']
			return 44
		case r == 125: // ['}','}']
			return 44
		case r == 126: // ['~','~']
			return 44
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 44
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 47
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 91: // ['[','[']
			return 50
		case r == 95: // ['_','_']
			return 51
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		case r == 123: // ['{','{']
			return 52
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 53
		case r == 61: // ['=','=']
			return 54
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 38: // ['&','&']
			return 55
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 56
		case r == 61: // ['=','=']
			return 57
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 58
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 59
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 60
		case r == 43: // ['+','+']
			return 61
		case r == 45: // ['-','-']
			return 62
		case r == 47: // ['/','/']
			return 63
		case 48 <= r && r <= 57: // ['0','9']
			return 64
		case r == 61: // ['=','=']
			return 65
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 47: // ['/','/']
			return 66
		case r == 61: // ['=','=']
			return 67
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 68
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		case 65 <= r && r <= 68: // ['A','D']
			return 24
		case r == 69: // ['E','E']
			return 69
		case 70 <= r && r <= 90: // ['F','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case r == 97: // ['a','a']
			return 24
		case r == 98: // ['b','b']
			return 70
		case 99 <= r && r <= 100: // ['c','d']
			return 24
		case r == 101: // ['e','e']
			return 69
		case 102 <= r && r <= 119: // ['f','w']
			return 24
		case r == 120: // ['x','x']
			return 71
		case 121 <= r && r <= 122: // ['y','z']
			return 24
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 68
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		case 65 <= r && r <= 68: // ['A','D']
			return 24
		case r == 69: // ['E','E']
			return 69
		case 70 <= r && r <= 90: // ['F','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 100: // ['a','d']
			return 24
		case r == 101: // ['e','e']
			return 69
		case 102 <= r && r <= 122: // ['f','z']
			return 24
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 60: // ['<','<']
			return 72
		case r == 61: // ['=','=']
			return 73
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 74
		case r == 126: // ['~','~']
			return 75
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 76
		case r == 62: // ['>','>']
			return 77
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 78
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case 65 <= r && r <= 90: // ['A','Z']
			return 80
		case r == 91: // ['[','[']
			return 81
		case r == 95: // ['_','_']
			return 82
		case 97 <= r && r <= 122: // ['a','z']
			return 80
		case r == 123: // ['{','{']
			return 83
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 72: // ['A','H']
			return 24
		case r == 73: // ['I','I']
			return 85
		case 74 <= r && r <= 77: // ['J','M']
			return 24
		case r == 78: // ['N','N']
			return 86
		case 79 <= r && r <= 90: // ['O','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 69: // ['A','E']
			return 24
		case r == 70: // ['F','F']
			return 87
		case 71 <= r && r <= 79: // ['G','O']
			return 24
		case r == 80: // ['P','P']
			return 88
		case r == 81: // ['Q','Q']
			return 24
		case r == 82: // ['R','R']
			return 89
		case 83 <= r && r <= 90: // ['S','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 90
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 69: // ['A','E']
			return 24
		case r == 70: // ['F','F']
			return 91
		case 71 <= r && r <= 81: // ['G','Q']
			return 24
		case r == 82: // ['R','R']
			return 92
		case 83 <= r && r <= 90: // ['S','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 69: // ['A','E']
			return 24
		case r == 70: // ['F','F']
			return 93
		case 71 <= r && r <= 79: // ['G','O']
			return 24
		case r == 80: // ['P','P']
			return 94
		case r == 81: // ['Q','Q']
			return 24
		case r == 82: // ['R','R']
			return 95
		case 83 <= r && r <= 90: // ['S','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 96
		case r == 94: // ['^','^']
			return 97
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 100: // ['a','d']
			return 24
		case r == 101: // ['e','e']
			return 98
		case 102 <= r && r <= 122: // ['f','z']
			return 24
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 108: // ['a','l']
			return 24
		case r == 109: // ['m','m']
			return 99
		case r == 110: // ['n','n']
			return 100
		case 111 <= r && r <= 122: // ['o','z']
			return 24
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case r == 97: // ['a','a']
			return 101
		case 98 <= r && r <= 104: // ['b','h']
			return 24
		case r == 105: // ['i','i']
			return 102
		case 106 <= r && r <= 107: // ['j','k']
			return 24
		case r == 108: // ['l','l']
			return 103
		case 109 <= r && r <= 122: // ['m','z']
			return 24
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 109: // ['a','m']
			return 24
		case r == 110: // ['n','n']
			return 104
		case 111 <= r && r <= 122: // ['o','z']
			return 24
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 113: // ['a','q']
			return 24
		case r == 114: // ['r','r']
			return 105
		case 115 <= r && r <= 122: // ['s','z']
			return 24
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 106
		case r == 124: // ['|','|']
			return 107
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case r == 126: // ['~','~']
			return 108
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 44
		case r == 33: // ['!','!']
			return 44
		case r == 34: // ['"','"']
			return 45
		case r == 35: // ['#','#']
			return 44
		case r == 36: // ['$','$']
			return 44
		case r == 37: // ['%','%']
			return 44
		case r == 38: // ['&','&']
			return 44
		case r == 39: // [''',''']
			return 44
		case r == 40: // ['(','(']
			return 44
		case r == 41: // [')',')']
			return 44
		case r == 42: // ['*','*']
			return 44
		case r == 43: // ['+','+']
			return 44
		case r == 44: // [',',',']
			return 44
		case r == 45: // ['-','-']
			return 44
		case r == 46: // ['.','.']
			return 44
		case r == 47: // ['/','/']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 44
		case r == 58: // [':',':']
			return 44
		case r == 59: // [';',';']
			return 44
		case r == 60: // ['<','<']
			return 44
		case r == 61: // ['=','=']
			return 44
		case r == 62: // ['>','>']
			return 44
		case r == 63: // ['?','?']
			return 44
		case r == 64: // ['@','@']
			return 44
		case 65 <= r && r <= 90: // ['A','Z']
			return 44
		case r == 91: // ['[','[']
			return 44
		case r == 92: // ['\','\']
			return 46
		case r == 93: // [']',']']
			return 44
		case r == 94: // ['^','^']
			return 44
		case r == 95: // ['_','_']
			return 44
		case r == 96: // ['`','`']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		case r == 123: // ['{','{']
			return 44
		case r == 124: // ['|','|']
			return 44
		case r == 125: // ['}','}']
			return 44
		case r == 126: // ['~','~']
			return 44
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 44
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 109
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 51
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 51
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 51
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 110
		case r == 33: // ['!','!']
			return 110
		case r == 35: // ['#','#']
			return 110
		case r == 36: // ['$','$']
			return 110
		case r == 37: // ['%','%']
			return 110
		case r == 38: // ['&','&']
			return 110
		case r == 39: // [''',''']
			return 110
		case r == 40: // ['(','(']
			return 110
		case r == 41: // [')',')']
			return 110
		case r == 42: // ['*','*']
			return 110
		case r == 43: // ['+','+']
			return 110
		case r == 44: // [',',',']
			return 110
		case r == 45: // ['-','-']
			return 110
		case r == 46: // ['.','.']
			return 110
		case r == 47: // ['/','/']
			return 110
		case 48 <= r && r <= 57: // ['0','9']
			return 110
		case r == 58: // [':',':']
			return 110
		case r == 59: // [';',';']
			return 110
		case r == 60: // ['<','<']
			return 110
		case r == 61: // ['=','=']
			return 110
		case r == 62: // ['>','>']
			return 110
		case r == 63: // ['?','?']
			return 110
		case r == 64: // ['@','@']
			return 110
		case 65 <= r && r <= 90: // ['A','Z']
			return 110
		case r == 91: // ['[','[']
			return 110
		case r == 92: // ['\','\']
			return 111
		case r == 93: // [']',']']
			return 110
		case r == 94: // ['^','^']
			return 110
		case r == 95: // ['_','_']
			return 110
		case r == 96: // ['`','`']
			return 110
		case 97 <= r && r <= 122: // ['a','z']
			return 110
		case r == 124: // ['|','|']
			return 110
		case r == 126: // ['~','~']
			return 110
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 110
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 112
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 113
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 114
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case r == 47: // ['/','/']
			return 115
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 64
		case r == 69: // ['E','E']
			return 116
		case r == 101: // ['e','e']
			return 116
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 117
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 118
		case r == 69: // ['E','E']
			return 119
		case r == 101: // ['e','e']
			return 119
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 120
		case 48 <= r && r <= 57: // ['0','9']
			return 121
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case 48 <= r && r <= 49: // ['0','1']
			return 122
		case 50 <= r && r <= 57: // ['2','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 123
		case 65 <= r && r <= 70: // ['A','F']
			return 124
		case 71 <= r && r <= 90: // ['G','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 102: // ['a','f']
			return 124
		case 103 <= r && r <= 122: // ['g','z']
			return 24
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 125
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 126
		case r == 62: // ['>','>']
			return 127
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case 65 <= r && r <= 90: // ['A','Z']
			return 80
		case r == 95: // ['_','_']
			return 82
		case 97 <= r && r <= 122: // ['a','z']
			return 80
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case 65 <= r && r <= 90: // ['A','Z']
			return 80
		case r == 95: // ['_','_']
			return 82
		case 97 <= r && r <= 122: // ['a','z']
			return 80
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case 65 <= r && r <= 90: // ['A','Z']
			return 80
		case r == 95: // ['_','_']
			return 82
		case 97 <= r && r <= 122: // ['a','z']
			return 80
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 128
		case r == 33: // ['!','!']
			return 128
		case r == 35: // ['#','#']
			return 128
		case r == 36: // ['$','$']
			return 128
		case r == 37: // ['%','%']
			return 128
		case r == 38: // ['&','&']
			return 128
		case r == 39: // [''',''']
			return 128
		case r == 40: // ['(','(']
			return 128
		case r == 41: // [')',')']
			return 128
		case r == 42: // ['*','*']
			return 128
		case r == 43: // ['+','+']
			return 128
		case r == 44: // [',',',']
			return 128
		case r == 45: // ['-','-']
			return 128
		case r == 46: // ['.','.']
			return 128
		case r == 47: // ['/','/']
			return 128
		case 48 <= r && r <= 57: // ['0','9']
			return 128
		case r == 58: // [':',':']
			return 128
		case r == 59: // [';',';']
			return 128
		case r == 60: // ['<','<']
			return 128
		case r == 61: // ['=','=']
			return 128
		case r == 62: // ['>','>']
			return 128
		case r == 63: // ['?','?']
			return 128
		case r == 64: // ['@','@']
			return 128
		case 65 <= r && r <= 90: // ['A','Z']
			return 128
		case r == 91: // ['[','[']
			return 128
		case r == 92: // ['\','\']
			return 129
		case r == 93: // [']',']']
			return 128
		case r == 94: // ['^','^']
			return 128
		case r == 95: // ['_','_']
			return 128
		case r == 96: // ['`','`']
			return 128
		case 97 <= r && r <= 122: // ['a','z']
			return 128
		case r == 124: // ['|','|']
			return 128
		case r == 126: // ['~','~']
			return 128
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 128
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 75: // ['A','K']
			return 24
		case r == 76: // ['L','L']
			return 130
		case 77 <= r && r <= 90: // ['M','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 81: // ['A','Q']
			return 24
		case r == 82: // ['R','R']
			return 131
		case 83 <= r && r <= 90: // ['S','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S87
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 82: // ['A','R']
			return 24
		case r == 83: // ['S','S']
			return 132
		case 84 <= r && r <= 90: // ['T','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 82: // ['A','R']
			return 24
		case r == 83: // ['S','S']
			return 133
		case 84 <= r && r <= 90: // ['T','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S89
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 82: // ['A','R']
			return 24
		case r == 83: // ['S','S']
			return 134
		case 84 <= r && r <= 90: // ['T','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S90
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 68: // ['A','D']
			return 24
		case r == 69: // ['E','E']
			return 135
		case 70 <= r && r <= 79: // ['F','O']
			return 24
		case r == 80: // ['P','P']
			return 136
		case 81 <= r && r <= 90: // ['Q','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S92
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S93
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 82: // ['A','R']
			return 24
		case r == 83: // ['S','S']
			return 137
		case 84 <= r && r <= 90: // ['T','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S94
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 82: // ['A','R']
			return 24
		case r == 83: // ['S','S']
			return 138
		case 84 <= r && r <= 90: // ['T','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S95
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 82: // ['A','R']
			return 24
		case r == 83: // ['S','S']
			return 139
		case 84 <= r && r <= 90: // ['T','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S96
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S97
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 140
		}
		return NoState
	},
	// S98
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 102: // ['a','f']
			return 24
		case r == 103: // ['g','g']
			return 141
		case 104 <= r && r <= 122: // ['h','z']
			return 24
		}
		return NoState
	},
	// S99
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 104: // ['a','h']
			return 24
		case r == 105: // ['i','i']
			return 142
		case 106 <= r && r <= 122: // ['j','z']
			return 24
		}
		return NoState
	},
	// S100
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 99: // ['a','c']
			return 24
		case r == 100: // ['d','d']
			return 143
		case 101 <= r && r <= 122: // ['e','z']
			return 24
		}
		return NoState
	},
	// S101
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 107: // ['a','k']
			return 24
		case r == 108: // ['l','l']
			return 144
		case 109 <= r && r <= 122: // ['m','z']
			return 24
		}
		return NoState
	},
	// S102
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 107: // ['a','k']
			return 24
		case r == 108: // ['l','l']
			return 145
		case 109 <= r && r <= 122: // ['m','z']
			return 24
		}
		return NoState
	},
	// S103
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 110: // ['a','n']
			return 24
		case r == 111: // ['o','o']
			return 146
		case 112 <= r && r <= 122: // ['p','z']
			return 24
		}
		return NoState
	},
	// S104
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 115: // ['a','s']
			return 24
		case r == 116: // ['t','t']
			return 147
		case 117 <= r && r <= 122: // ['u','z']
			return 24
		}
		return NoState
	},
	// S105
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 116: // ['a','t']
			return 24
		case r == 117: // ['u','u']
			return 148
		case 118 <= r && r <= 122: // ['v','z']
			return 24
		}
		return NoState
	},
	// S106
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S107
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 149
		}
		return NoState
	},
	// S108
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S109
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 44
		case r == 33: // ['!','!']
			return 44
		case r == 34: // ['"','"']
			return 45
		case r == 35: // ['#','#']
			return 44
		case r == 36: // ['$','$']
			return 44
		case r == 37: // ['%','%']
			return 44
		case r == 38: // ['&','&']
			return 44
		case r == 39: // [''',''']
			return 44
		case r == 40: // ['(','(']
			return 44
		case r == 41: // [')',')']
			return 44
		case r == 42: // ['*','*']
			return 44
		case r == 43: // ['+','+']
			return 44
		case r == 44: // [',',',']
			return 44
		case r == 45: // ['-','-']
			return 44
		case r == 46: // ['.','.']
			return 44
		case r == 47: // ['/','/']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 44
		case r == 58: // [':',':']
			return 44
		case r == 59: // [';',';']
			return 44
		case r == 60: // ['<','<']
			return 44
		case r == 61: // ['=','=']
			return 44
		case r == 62: // ['>','>']
			return 44
		case r == 63: // ['?','?']
			return 44
		case r == 64: // ['@','@']
			return 44
		case 65 <= r && r <= 90: // ['A','Z']
			return 44
		case r == 91: // ['[','[']
			return 44
		case r == 92: // ['\','\']
			return 46
		case r == 93: // [']',']']
			return 44
		case r == 94: // ['^','^']
			return 44
		case r == 95: // ['_','_']
			return 44
		case r == 96: // ['`','`']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 44
		case r == 123: // ['{','{']
			return 44
		case r == 124: // ['|','|']
			return 44
		case r == 125: // ['}','}']
			return 44
		case r == 126: // ['~','~']
			return 44
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 44
		}
		return NoState
	},
	// S110
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 110
		case r == 33: // ['!','!']
			return 110
		case r == 35: // ['#','#']
			return 110
		case r == 36: // ['$','$']
			return 110
		case r == 37: // ['%','%']
			return 110
		case r == 38: // ['&','&']
			return 110
		case r == 39: // [''',''']
			return 110
		case r == 40: // ['(','(']
			return 110
		case r == 41: // [')',')']
			return 110
		case r == 42: // ['*','*']
			return 110
		case r == 43: // ['+','+']
			return 110
		case r == 44: // [',',',']
			return 110
		case r == 45: // ['-','-']
			return 110
		case r == 46: // ['.','.']
			return 110
		case r == 47: // ['/','/']
			return 110
		case 48 <= r && r <= 57: // ['0','9']
			return 110
		case r == 58: // [':',':']
			return 110
		case r == 59: // [';',';']
			return 110
		case r == 60: // ['<','<']
			return 110
		case r == 61: // ['=','=']
			return 110
		case r == 62: // ['>','>']
			return 110
		case r == 63: // ['?','?']
			return 110
		case r == 64: // ['@','@']
			return 110
		case 65 <= r && r <= 90: // ['A','Z']
			return 110
		case r == 91: // ['[','[']
			return 110
		case r == 92: // ['\','\']
			return 150
		case r == 93: // [']',']']
			return 110
		case r == 94: // ['^','^']
			return 110
		case r == 95: // ['_','_']
			return 110
		case r == 96: // ['`','`']
			return 110
		case 97 <= r && r <= 122: // ['a','z']
			return 110
		case r == 124: // ['|','|']
			return 110
		case r == 125: // ['}','}']
			return 151
		case r == 126: // ['~','~']
			return 110
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 110
		}
		return NoState
	},
	// S111
	func(r rune) int {
		switch {
		case r == 123: // ['{','{']
			return 110
		case r == 125: // ['}','}']
			return 152
		}
		return NoState
	},
	// S112
	func(r rune) int {
		switch {
		case r == 112: // ['p','p']
			return 153
		}
		return NoState
	},
	// S113
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S114
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S115
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S116
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 154
		case 48 <= r && r <= 57: // ['0','9']
			return 155
		}
		return NoState
	},
	// S117
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S118
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 118
		case r == 69: // ['E','E']
			return 156
		case r == 101: // ['e','e']
			return 156
		}
		return NoState
	},
	// S119
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 157
		case 48 <= r && r <= 57: // ['0','9']
			return 158
		}
		return NoState
	},
	// S120
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 159
		}
		return NoState
	},
	// S121
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 121
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S122
	func(r rune) int {
		switch {
		case 48 <= r && r <= 49: // ['0','1']
			return 122
		case 50 <= r && r <= 57: // ['2','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S123
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 123
		case 65 <= r && r <= 70: // ['A','F']
			return 124
		case 71 <= r && r <= 90: // ['G','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 102: // ['a','f']
			return 124
		case 103 <= r && r <= 122: // ['g','z']
			return 24
		}
		return NoState
	},
	// S124
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 123
		case 65 <= r && r <= 70: // ['A','F']
			return 124
		case 71 <= r && r <= 90: // ['G','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 102: // ['a','f']
			return 124
		case 103 <= r && r <= 122: // ['g','z']
			return 24
		}
		return NoState
	},
	// S125
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S126
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S127
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 160
		}
		return NoState
	},
	// S128
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 128
		case r == 33: // ['!','!']
			return 128
		case r == 35: // ['#','#']
			return 128
		case r == 36: // ['$','$']
			return 128
		case r == 37: // ['%','%']
			return 128
		case r == 38: // ['&','&']
			return 128
		case r == 39: // [''',''']
			return 128
		case r == 40: // ['(','(']
			return 128
		case r == 41: // [')',')']
			return 128
		case r == 42: // ['*','*']
			return 128
		case r == 43: // ['+','+']
			return 128
		case r == 44: // [',',',']
			return 128
		case r == 45: // ['-','-']
			return 128
		case r == 46: // ['.','.']
			return 128
		case r == 47: // ['/','/']
			return 128
		case 48 <= r && r <= 57: // ['0','9']
			return 128
		case r == 58: // [':',':']
			return 128
		case r == 59: // [';',';']
			return 128
		case r == 60: // ['<','<']
			return 128
		case r == 61: // ['=','=']
			return 128
		case r == 62: // ['>','>']
			return 128
		case r == 63: // ['?','?']
			return 128
		case r == 64: // ['@','@']
			return 128
		case 65 <= r && r <= 90: // ['A','Z']
			return 128
		case r == 91: // ['[','[']
			return 128
		case r == 92: // ['\','\']
			return 161
		case r == 93: // [']',']']
			return 128
		case r == 94: // ['^','^']
			return 128
		case r == 95: // ['_','_']
			return 128
		case r == 96: // ['`','`']
			return 128
		case 97 <= r && r <= 122: // ['a','z']
			return 128
		case r == 124: // ['|','|']
			return 128
		case r == 125: // ['}','}']
			return 162
		case r == 126: // ['~','~']
			return 128
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 128
		}
		return NoState
	},
	// S129
	func(r rune) int {
		switch {
		case r == 123: // ['{','{']
			return 128
		case r == 125: // ['}','}']
			return 163
		}
		return NoState
	},
	// S130
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 68: // ['A','D']
			return 24
		case r == 69: // ['E','E']
			return 164
		case 70 <= r && r <= 90: // ['F','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S131
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S132
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S133
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S134
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S135
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S136
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 72: // ['A','H']
			return 24
		case r == 73: // ['I','I']
			return 165
		case 74 <= r && r <= 90: // ['J','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S137
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S138
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S139
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S140
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S141
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 104: // ['a','h']
			return 24
		case r == 105: // ['i','i']
			return 166
		case 106 <= r && r <= 122: // ['j','z']
			return 24
		}
		return NoState
	},
	// S142
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 115: // ['a','s']
			return 24
		case r == 116: // ['t','t']
			return 167
		case 117 <= r && r <= 122: // ['u','z']
			return 24
		}
		return NoState
	},
	// S143
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S144
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 114: // ['a','r']
			return 24
		case r == 115: // ['s','s']
			return 168
		case 116 <= r && r <= 122: // ['t','z']
			return 24
		}
		return NoState
	},
	// S145
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 115: // ['a','s']
			return 24
		case r == 116: // ['t','t']
			return 169
		case 117 <= r && r <= 122: // ['u','z']
			return 24
		}
		return NoState
	},
	// S146
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case r == 97: // ['a','a']
			return 170
		case 98 <= r && r <= 122: // ['b','z']
			return 24
		}
		return NoState
	},
	// S147
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S148
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 100: // ['a','d']
			return 24
		case r == 101: // ['e','e']
			return 171
		case 102 <= r && r <= 122: // ['f','z']
			return 24
		}
		return NoState
	},
	// S149
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S150
	func(r rune) int {
		switch {
		case r == 123: // ['{','{']
			return 110
		case r == 125: // ['}','}']
			return 152
		}
		return NoState
	},
	// S151
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S152
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 110
		case r == 33: // ['!','!']
			return 110
		case r == 35: // ['#','#']
			return 110
		case r == 36: // ['$','$']
			return 110
		case r == 37: // ['%','%']
			return 110
		case r == 38: // ['&','&']
			return 110
		case r == 39: // [''',''']
			return 110
		case r == 40: // ['(','(']
			return 110
		case r == 41: // [')',')']
			return 110
		case r == 42: // ['*','*']
			return 110
		case r == 43: // ['+','+']
			return 110
		case r == 44: // [',',',']
			return 110
		case r == 45: // ['-','-']
			return 110
		case r == 46: // ['.','.']
			return 110
		case r == 47: // ['/','/']
			return 110
		case 48 <= r && r <= 57: // ['0','9']
			return 110
		case r == 58: // [':',':']
			return 110
		case r == 59: // [';',';']
			return 110
		case r == 60: // ['<','<']
			return 110
		case r == 61: // ['=','=']
			return 110
		case r == 62: // ['>','>']
			return 110
		case r == 63: // ['?','?']
			return 110
		case r == 64: // ['@','@']
			return 110
		case 65 <= r && r <= 90: // ['A','Z']
			return 110
		case r == 91: // ['[','[']
			return 110
		case r == 92: // ['\','\']
			return 150
		case r == 93: // [']',']']
			return 110
		case r == 94: // ['^','^']
			return 110
		case r == 95: // ['_','_']
			return 110
		case r == 96: // ['`','`']
			return 110
		case 97 <= r && r <= 122: // ['a','z']
			return 110
		case r == 124: // ['|','|']
			return 110
		case r == 125: // ['}','}']
			return 151
		case r == 126: // ['~','~']
			return 110
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 110
		}
		return NoState
	},
	// S153
	func(r rune) int {
		switch {
		case r == 97: // ['a','a']
			return 172
		}
		return NoState
	},
	// S154
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 173
		}
		return NoState
	},
	// S155
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 155
		}
		return NoState
	},
	// S156
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 174
		case 48 <= r && r <= 57: // ['0','9']
			return 175
		}
		return NoState
	},
	// S157
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 176
		}
		return NoState
	},
	// S158
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 158
		}
		return NoState
	},
	// S159
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 159
		}
		return NoState
	},
	// S160
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S161
	func(r rune) int {
		switch {
		case r == 123: // ['{','{']
			return 128
		case r == 125: // ['}','}']
			return 163
		}
		return NoState
	},
	// S162
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S163
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 128
		case r == 33: // ['!','!']
			return 128
		case r == 35: // ['#','#']
			return 128
		case r == 36: // ['$','$']
			return 128
		case r == 37: // ['%','%']
			return 128
		case r == 38: // ['&','&']
			return 128
		case r == 39: // [''',''']
			return 128
		case r == 40: // ['(','(']
			return 128
		case r == 41: // [')',')']
			return 128
		case r == 42: // ['*','*']
			return 128
		case r == 43: // ['+','+']
			return 128
		case r == 44: // [',',',']
			return 128
		case r == 45: // ['-','-']
			return 128
		case r == 46: // ['.','.']
			return 128
		case r == 47: // ['/','/']
			return 128
		case 48 <= r && r <= 57: // ['0','9']
			return 128
		case r == 58: // [':',':']
			return 128
		case r == 59: // [';',';']
			return 128
		case r == 60: // ['<','<']
			return 128
		case r == 61: // ['=','=']
			return 128
		case r == 62: // ['>','>']
			return 128
		case r == 63: // ['?','?']
			return 128
		case r == 64: // ['@','@']
			return 128
		case 65 <= r && r <= 90: // ['A','Z']
			return 128
		case r == 91: // ['[','[']
			return 128
		case r == 92: // ['\','\']
			return 161
		case r == 93: // [']',']']
			return 128
		case r == 94: // ['^','^']
			return 128
		case r == 95: // ['_','_']
			return 128
		case r == 96: // ['`','`']
			return 128
		case 97 <= r && r <= 122: // ['a','z']
			return 128
		case r == 124: // ['|','|']
			return 128
		case r == 125: // ['}','}']
			return 162
		case r == 126: // ['~','~']
			return 128
		case 256 <= r && r <= 1114111: // [\u0100,\U0010ffff]
			return 128
		}
		return NoState
	},
	// S164
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 77: // ['A','M']
			return 24
		case r == 78: // ['N','N']
			return 177
		case 79 <= r && r <= 90: // ['O','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S165
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S166
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 109: // ['a','m']
			return 24
		case r == 110: // ['n','n']
			return 178
		case 111 <= r && r <= 122: // ['o','z']
			return 24
		}
		return NoState
	},
	// S167
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S168
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 100: // ['a','d']
			return 24
		case r == 101: // ['e','e']
			return 179
		case 102 <= r && r <= 122: // ['f','z']
			return 24
		}
		return NoState
	},
	// S169
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 100: // ['a','d']
			return 24
		case r == 101: // ['e','e']
			return 180
		case 102 <= r && r <= 122: // ['f','z']
			return 24
		}
		return NoState
	},
	// S170
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 115: // ['a','s']
			return 24
		case r == 116: // ['t','t']
			return 181
		case 117 <= r && r <= 122: // ['u','z']
			return 24
		}
		return NoState
	},
	// S171
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S172
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 182
		}
		return NoState
	},
	// S173
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 173
		}
		return NoState
	},
	// S174
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 183
		}
		return NoState
	},
	// S175
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 175
		}
		return NoState
	},
	// S176
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 176
		}
		return NoState
	},
	// S177
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case r == 65: // ['A','A']
			return 184
		case 66 <= r && r <= 84: // ['B','T']
			return 24
		case r == 85: // ['U','U']
			return 185
		case 86 <= r && r <= 90: // ['V','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S178
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S179
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S180
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 113: // ['a','q']
			return 24
		case r == 114: // ['r','r']
			return 186
		case 115 <= r && r <= 122: // ['s','z']
			return 24
		}
		return NoState
	},
	// S181
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S182
	func(r rune) int {
		switch {
		case r == 105: // ['i','i']
			return 187
		}
		return NoState
	},
	// S183
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 183
		}
		return NoState
	},
	// S184
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 76: // ['A','L']
			return 24
		case r == 77: // ['M','M']
			return 188
		case 78 <= r && r <= 90: // ['N','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S185
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 76: // ['A','L']
			return 24
		case r == 77: // ['M','M']
			return 189
		case 78 <= r && r <= 90: // ['N','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S186
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S187
	func(r rune) int {
		switch {
		case r == 99: // ['c','c']
			return 190
		}
		return NoState
	},
	// S188
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 68: // ['A','D']
			return 24
		case r == 69: // ['E','E']
			return 191
		case 70 <= r && r <= 90: // ['F','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S189
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S190
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 192
		}
		return NoState
	},
	// S191
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S192
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 193
		}
		return NoState
	},
	// S193
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 194
		}
		return NoState
	},
	// S194
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
