// Package parsing contains the single source file mlr.bnf, which is the
// lexical/semantic grammar file for the Miller put/filter DSL using the PGPG
// framework. Go source files are autogenerated by PGPG.
package parsing
