package completion

// bashScript is the bash completion shim emitted by `mlr completion bash`. It
// holds no knowledge of Miller's grammar: it forwards the current words to
// `mlr completion complete`, which returns a one-line directive followed by
// candidate words.
const bashScript = `# bash completion for mlr -- generated by 'mlr completion bash'
_mlr_complete() {
    local IFS=$'\n'
    local response
    response=( $("${COMP_WORDS[0]}" completion complete "$COMP_CWORD" "${COMP_WORDS[@]}" 2>/dev/null) )

    local directive="${response[0]}"
    local candidates=( "${response[@]:1}" )

    COMPREPLY=()
    case "$directive" in
        files)
            compopt -o default 2>/dev/null
            ;;
        default)
            compopt -o default 2>/dev/null
            COMPREPLY=( "${candidates[@]}" )
            ;;
        *)
            COMPREPLY=( "${candidates[@]}" )
            ;;
    esac
}
complete -F _mlr_complete mlr
`

// zshScript is the zsh completion shim emitted by `mlr completion zsh`.
const zshScript = `#compdef mlr
# zsh completion for mlr -- generated by 'mlr completion zsh'
_mlr() {
    local -a response candidates
    local directive
    response=("${(@f)$(${words[1]} completion complete $((CURRENT-1)) "${words[@]}" 2>/dev/null)}")

    directive=${response[1]}
    candidates=(${response[2,-1]})

    case $directive in
        files)
            _files
            ;;
        default)
            (( ${#candidates} )) && compadd -- ${candidates}
            _files
            ;;
        *)
            compadd -- ${candidates}
            ;;
    esac
}
compdef _mlr mlr
`
