all: catc catc0 catm catrust catgo catnim cutgo cutnim
# catd cutd
allc: catc catc0 catm

catc: catc.c
	gcc -Wall catc.c -o catc
catc0: catc0.c
	gcc -Wall catc0.c -o catc0
catm: catm.c
	gcc -Wall catm.c -o catm
#catd: catd.d
#	dmd -O catd.d
catrust: catrust.rs
	rustc catrust.rs
catgo: catgo.go
	go build catgo.go
catnim: catnim.nim
	nim compile catnim.nim
#cutd: cutd.d
#	dmd -O cutd.d
cutgo: cutgo.go
	go build cutgo.go
cutnim: cutnim.nim
	nim compile cutnim.nim
