all: catc catc0 catm

catc: catc.c
	gcc -Wall catc.c -o catc
catc0: catc0.c
	gcc -Wall catc0.c -o catc0
catm: catm.c
	gcc -Wall catm.c -o catm
catd: catd.d
	dmd -O catd.d
catgo: catgo.go
	go build catgo.go
catrust: catrust.rs
	rustc catrust.rs
cutd: cutd.d
	dmd -O cutd.d
cutgo: cutgo.go
	go build cutgo.go
