#!/bin/bash
if [ $# -eq 1 -a "$1" = "index.rst" ]; then
  true
elif [ $# -ge 1 ]; then
  for name; do
    if [[ $name == *.rst.in ]]; then
      genrst $name;
    fi
  done
else
  for rstin in *.rst.in; do genrst $rstin; done
fi
sphinx-build -M html . _build
