#!/bin/bash

if [ $# -ge 1 ]; then
  for f in $*; do
    echo $f ...
    ./morph < $f > tmp.$f && mv tmp.$f $f
  done
else
  for f in *.rst.in; do
    echo $f ...
    ./morph < $f > tmp.$f && mv tmp.$f $f
  done
fi
