// Code generated by gocc; DO NOT EDIT.

package token

import (
	"bytes"
	"fmt"
	"strconv"
	"unicode/utf8"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset  int
	Line    int
	Column  int
	Context Context
}

func (p Pos) String() string {
	// If the context provides a filename, provide a human-readable File:Line:Column representation.
	switch src := p.Context.(type) {
	case Sourcer:
		return fmt.Sprintf("%s:%d:%d", src.Source(), p.Line, p.Column)
	default:
		return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
	}
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

// Equals returns returns true if the token Type and Lit are matches.
func (t *Token) Equals(rhs interface{}) bool {
	switch rhsT := rhs.(type) {
	case *Token:
		return t == rhsT || (t.Type == rhsT.Type && bytes.Equal(t.Lit, rhsT.Lit))
	default:
		return false
	}
}

// CharLiteralValue returns the string value of the char literal.
func (t *Token) CharLiteralValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

// Float32Value returns the float32 value of the token or an error if the token literal does not
// denote a valid float32.
func (t *Token) Float32Value() (float32, error) {
	if v, err := strconv.ParseFloat(string(t.Lit), 32); err != nil {
		return 0, err
	} else {
		return float32(v), nil
	}
}

// Float64Value returns the float64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Float64Value() (float64, error) {
	return strconv.ParseFloat(string(t.Lit), 64)
}

// IDValue returns the string representation of an identifier token.
func (t *Token) IDValue() string {
	return string(t.Lit)
}

// Int32Value returns the int32 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int32Value() (int32, error) {
	if v, err := strconv.ParseInt(string(t.Lit), 10, 64); err != nil {
		return 0, err
	} else {
		return int32(v), nil
	}
}

// Int64Value returns the int64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int64Value() (int64, error) {
	return strconv.ParseInt(string(t.Lit), 10, 64)
}

// UTF8Rune decodes the UTF8 rune in the token literal. It returns utf8.RuneError if
// the token literal contains an invalid rune.
func (t *Token) UTF8Rune() (rune, error) {
	r, _ := utf8.DecodeRune(t.Lit)
	if r == utf8.RuneError {
		err := fmt.Errorf("Invalid rune")
		return r, err
	}
	return r, nil
}

// StringValue returns the string value of the token literal.
func (t *Token) StringValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"empty",
		";",
		"{",
		"}",
		"=",
		"unset",
		"filter",
		">",
		">>",
		"|",
		"stdout",
		"stderr",
		"print",
		",",
		"printn",
		"eprint",
		"eprintn",
		"dump",
		"edump",
		"tee",
		"emitf",
		"emit1",
		"emit",
		"(",
		")",
		"emitp",
		"exit",
		"field_name",
		"$[",
		"]",
		"braced_field_name",
		"$[[",
		"$[[[",
		"full_srec",
		"oosvar_name",
		"@[",
		"braced_oosvar_name",
		"full_oosvar",
		"all",
		"non_sigil_name",
		"arr",
		"bool",
		"float",
		"int",
		"map",
		"num",
		"str",
		"var",
		"funct",
		"||=",
		"^^=",
		"&&=",
		"??=",
		"???=",
		"|=",
		"&=",
		"^=",
		"<<=",
		">>=",
		">>>=",
		"+=",
		".=",
		"-=",
		"*=",
		"/=",
		"//=",
		"%=",
		"**=",
		"?",
		":",
		"||",
		"^^",
		"&&",
		"??",
		"???",
		"=~",
		"!=~",
		"==",
		"!=",
		"<=>",
		">=",
		"<",
		"<=",
		"^",
		"&",
		"<<",
		">>>",
		"+",
		"-",
		".+",
		".-",
		"*",
		"/",
		"//",
		"%",
		".*",
		"./",
		".//",
		".",
		"!",
		"~",
		"**",
		"string_literal",
		"regex_case_insensitive",
		"int_literal",
		"float_literal",
		"boolean_literal",
		"null_literal",
		"inf_literal",
		"nan_literal",
		"const_M_PI",
		"const_M_E",
		"panic",
		"[",
		"ctx_IPS",
		"ctx_IFS",
		"ctx_IRS",
		"ctx_OPS",
		"ctx_OFS",
		"ctx_ORS",
		"ctx_FLATSEP",
		"ctx_NF",
		"ctx_NR",
		"ctx_FNR",
		"ctx_FILENAME",
		"ctx_FILENUM",
		"env",
		"[[",
		"[[[",
		"call",
		"begin",
		"end",
		"if",
		"elif",
		"else",
		"while",
		"do",
		"for",
		"in",
		"break",
		"continue",
		"func",
		"subr",
		"return",
	},

	idMap: map[string]Type{
		"INVALID":                0,
		"$":                      1,
		"empty":                  2,
		";":                      3,
		"{":                      4,
		"}":                      5,
		"=":                      6,
		"unset":                  7,
		"filter":                 8,
		">":                      9,
		">>":                     10,
		"|":                      11,
		"stdout":                 12,
		"stderr":                 13,
		"print":                  14,
		",":                      15,
		"printn":                 16,
		"eprint":                 17,
		"eprintn":                18,
		"dump":                   19,
		"edump":                  20,
		"tee":                    21,
		"emitf":                  22,
		"emit1":                  23,
		"emit":                   24,
		"(":                      25,
		")":                      26,
		"emitp":                  27,
		"exit":                   28,
		"field_name":             29,
		"$[":                     30,
		"]":                      31,
		"braced_field_name":      32,
		"$[[":                    33,
		"$[[[":                   34,
		"full_srec":              35,
		"oosvar_name":            36,
		"@[":                     37,
		"braced_oosvar_name":     38,
		"full_oosvar":            39,
		"all":                    40,
		"non_sigil_name":         41,
		"arr":                    42,
		"bool":                   43,
		"float":                  44,
		"int":                    45,
		"map":                    46,
		"num":                    47,
		"str":                    48,
		"var":                    49,
		"funct":                  50,
		"||=":                    51,
		"^^=":                    52,
		"&&=":                    53,
		"??=":                    54,
		"???=":                   55,
		"|=":                     56,
		"&=":                     57,
		"^=":                     58,
		"<<=":                    59,
		">>=":                    60,
		">>>=":                   61,
		"+=":                     62,
		".=":                     63,
		"-=":                     64,
		"*=":                     65,
		"/=":                     66,
		"//=":                    67,
		"%=":                     68,
		"**=":                    69,
		"?":                      70,
		":":                      71,
		"||":                     72,
		"^^":                     73,
		"&&":                     74,
		"??":                     75,
		"???":                    76,
		"=~":                     77,
		"!=~":                    78,
		"==":                     79,
		"!=":                     80,
		"<=>":                    81,
		">=":                     82,
		"<":                      83,
		"<=":                     84,
		"^":                      85,
		"&":                      86,
		"<<":                     87,
		">>>":                    88,
		"+":                      89,
		"-":                      90,
		".+":                     91,
		".-":                     92,
		"*":                      93,
		"/":                      94,
		"//":                     95,
		"%":                      96,
		".*":                     97,
		"./":                     98,
		".//":                    99,
		".":                      100,
		"!":                      101,
		"~":                      102,
		"**":                     103,
		"string_literal":         104,
		"regex_case_insensitive": 105,
		"int_literal":            106,
		"float_literal":          107,
		"boolean_literal":        108,
		"null_literal":           109,
		"inf_literal":            110,
		"nan_literal":            111,
		"const_M_PI":             112,
		"const_M_E":              113,
		"panic":                  114,
		"[":                      115,
		"ctx_IPS":                116,
		"ctx_IFS":                117,
		"ctx_IRS":                118,
		"ctx_OPS":                119,
		"ctx_OFS":                120,
		"ctx_ORS":                121,
		"ctx_FLATSEP":            122,
		"ctx_NF":                 123,
		"ctx_NR":                 124,
		"ctx_FNR":                125,
		"ctx_FILENAME":           126,
		"ctx_FILENUM":            127,
		"env":                    128,
		"[[":                     129,
		"[[[":                    130,
		"call":                   131,
		"begin":                  132,
		"end":                    133,
		"if":                     134,
		"elif":                   135,
		"else":                   136,
		"while":                  137,
		"do":                     138,
		"for":                    139,
		"in":                     140,
		"break":                  141,
		"continue":               142,
		"func":                   143,
		"subr":                   144,
		"return":                 145,
	},
}
