#!/bin/bash

set -euo pipefail

export GOPATH=$(pwd)

# Override GOCC codegen with customized error handling
cp src/miller/parsing/errors.go.template src/miller/parsing/errors/errors.go

go build mlr.go
cp mlr mlrgo
echo "Compile OK"
