#!/bin/bash

# ================================================================
# Reads the Miller DSL grammar file and generates Go code.
# ================================================================

set -euo pipefail

verbose="false"
if [ $# -eq 1 ]; then
  if [ "$1" == "-v" ]; then
    verbose="true"
  fi
fi

# Build the bin/gocc executable:
###### go get github.com/goccmack/gocc
mkdir -p ./bin
go build github.com/goccmack/gocc
mv gocc ./bin/

rm -f src/parsing/*.txt
if [ "$verbose" = "true" ]; then
  lr1="src/parsing/LR1_conflicts.txt"
  ./bin/gocc -v -o ./src/parsing -p miller/src/parsing src/parsing/mlr.bnf || expand -2 $lr1
else
  ./bin/gocc -o ./src/parsing -p miller/src/parsing src/parsing/mlr.bnf
fi

# Code-gen directories:
#   src/parsing/errors/
#   src/parsing/lexer/
#   src/parsing/parser/
#   src/parsing/token/
#   src/parsing/util/

# Override GOCC codegen with customized error handling
cp src/parsing/errors.go.template src/parsing/errors/errors.go

for x in src/parsing/*/*.go; do gofmt -w $x; done
