#!/bin/bash

verbose=""
if [ "$1" = "-v" ]; then
  set -x
  verbose="-v"
fi

set -euo pipefail

echo ================================================================
echo BUILD
go build mlr.go
echo Compile OK
echo

# During the C-to-Go port I like to have ../c/mlr and ./mlrgo and have symlinks
# to them from my ~/lbin. Hence the duplicate name here.
cp mlr mlrgo

echo ================================================================
echo UNIT TESTS
go test ./...
echo

echo ================================================================
echo REGRESSION TESTS v2
echo
mlr regtest reg-test/cases reg-test/cases-pending-windows $verbose
echo

echo ================================================================
echo REGRESSION TESTS v1
echo
./reg-test/run -n $verbose
