#!/bin/bash

verbose=""
do_wips="false"
if [ "$1" = "-v" ]; then
  shift
  set -x
  verbose="-v"
fi
if [ "$1" = "-x" ]; then
  shift
  do_wips="true"
fi

if [ "$do_wips" = "false" ]; then
  set -euo pipefail
fi

echo ================================================================
echo BUILD
go build mlr.go
echo Compile OK
echo

# During the C-to-Go port I like to have ../c/mlr and ./mlrgo and have symlinks
# to them from my ~/lbin. Hence the duplicate name here.
cp mlr mlrgo

echo ================================================================
echo UNIT TESTS
go test -v miller/src/...
# 'go test' (with no arguments) is the same as 'mlr regtest'

echo
echo ================================================================
echo REGRESSION TESTS MAIN
echo
mlr regtest $verbose regtest/cases

if [ "$do_wips" = "true" ]; then

  echo
  echo ================================================================
  echo REGRESSION TESTS PENDING WINDOWS
  echo
  mlr regtest $verbose cases-pending-windows

  echo
  echo ================================================================
  echo REGRESSION TESTS PENDING GO PORT
  echo
  mlr regtest $verbose regtest/cases-pending-go-port
fi
echo

# Run the auto-formatter
go fmt ./...
