#!/bin/bash

verbose=""
do_wips="false"
if [ "$1" = "-v" ]; then
  shift
  set -x
  verbose="-v"
fi
if [ "$1" = "-x" ]; then
  shift
  do_wips="true"
fi

if [ "$do_wips" = "false" ]; then
  set -euo pipefail
fi

echo ================================================================
echo BUILD
go build mlr.go
echo Compile OK
echo

# During the C-to-Go port I like to have ../c/mlr and ./mlrgo and have symlinks
# to them from my ~/lbin. Hence the duplicate name here.
cp mlr mlrgo

echo ================================================================
echo UNIT TESTS
go test ./...

echo
echo ================================================================
echo REGRESSION TESTS v2 MAIN
echo
mlr regtest $verbose reg-test/cases reg-test/cases-pending-windows

if [ "$do_wips" = "true" ]; then
  echo
  echo ================================================================
  echo REGRESSION TESTS v2 PENDING GO PORT
  echo
  mlr regtest $verbose reg-test/cases-pending-go-port
fi
echo

echo
if [ "$do_wips" = "true" ]; then
  echo
  echo ================================================================
  echo REGRESSION TESTS v1
  ./reg-test/run $verbose
fi
