#!/bin/bash

path_to_mlr="./mlr"
indir="./reg-test/input"

build-go
if [ $? -ne 0 ]; then
  exit 1
fi

# ----------------------------------------------------------------
run_mlr() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
}

# ----------------------------------------------------------------
mlr_expect_fail() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
  status=$?
  if [ $status -eq 0 ]; then
    echo "failed to fail"
  fi
}

# ----------------------------------------------------------------
run_cat() {
  echo
  echo cat "$@"
  echo
  cat "$@"
}

# ----------------------------------------------------------------
announce() {
  echo
  echo "================================================================"
  echo
  echo "$@"
}

# ----------------------------------------------------------------
mention() {
  echo
  echo ---------------------------------------------------------------- "$@"
}

# ================================================================
#path_to_mlr="../c/mlr"
path_to_mlr="../go/mlr"

#vflag="-v"
vflag=""

#input="-n"
input="--from $indir/2.dkvp"

mention print
run_mlr $input put $vflag '@x=1; print'
run_mlr $input put $vflag '@x=1; print > stdout'
run_mlr $input put $vflag '@x=1; print @x'
run_mlr $input put $vflag '@x=1; print > stdout, @x'

mention printn
run_mlr $input put $vflag '@x=1; printn'
run_mlr $input put $vflag '@x=1; printn > stdout'
run_mlr $input put $vflag '@x=1; printn @x'
run_mlr $input put $vflag '@x=1; printn > stdout, @x'

mention eprint
run_mlr $input put $vflag '@x=1; eprint'
run_mlr $input put $vflag '@x=1; eprint @x'

mention eprintn
run_mlr $input put $vflag '@x=1; eprintn'
run_mlr $input put $vflag '@x=1; eprintn @x'

mention dump
run_mlr $input put $vflag '@x=1; dump'
run_mlr $input put $vflag '@x=1; dump > stdout'
run_mlr $input put $vflag '@x=1; dump @x'
run_mlr $input put $vflag '@x=1; dump > stdout, @x'
#run_mlr $input put $vflag '@x=1; dump > stdout @x'

mention edump
run_mlr $input put $vflag '@x=1; edump'
run_mlr $input put $vflag '@x=1; edump @x'

mention tee
run_mlr $input put $vflag '@x=1; tee > stdout, $*'

mention emitf
run_mlr $input put $vflag '@x=1; emitf @x'
run_mlr $input put $vflag '@x=1; emitf > stdout, @x'

mention emit
run_mlr $input put $vflag '@x=1; emit @x'
run_mlr $input put $vflag '@x=1; emit > stdout, @x'
run_mlr $input put $vflag '@x=1; @y=2; emit (@x, @y)'
run_mlr $input put $vflag '@x=1; @y=2; emit > stdout, (@x, @y)'

run_mlr $input put $vflag '@x={"a":1}; emit @x, "a"'
run_mlr $input put $vflag '@x={"a":1}; emit > stdout, @x, "a"'
run_mlr $input put $vflag '@x={"a":1}; @y={"a":2}; emit (@x, @y), "a"'
run_mlr $input put $vflag '@x={"a":1}; @y={"a":2}; emit > stdout, (@x, @y), "a"'

mention emitp
run_mlr $input put $vflag '@x=1; emitp @x'
run_mlr $input put $vflag '@x=1; emitp > stdout, @x'
run_mlr $input put $vflag '@x=1; @y=2; emitp (@x, @y)'
run_mlr $input put $vflag '@x=1; @y=2; emitp > stdout, (@x, @y)'

run_mlr $input put $vflag '@x={"a":1}; emitp @x, "a"'
run_mlr $input put $vflag '@x={"a":1}; emitp > stdout, @x, "a"'
run_mlr $input put $vflag '@x={"a":1}; @y={"a":2}; emitp (@x, @y), "a"'
run_mlr $input put $vflag '@x={"a":1}; @y={"a":2}; emitp > stdout, (@x, @y), "a"'

# ================================================================
