#!/bin/bash

path_to_mlr="./mlr"
indir="./reg-test/input"

build-go
if [ $? -ne 0 ]; then
  exit 1
fi

# ----------------------------------------------------------------
run_mlr() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
}

# ----------------------------------------------------------------
mlr_expect_fail() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
  status=$?
  if [ $status -eq 0 ]; then
    echo "failed to fail"
  fi
}

# ----------------------------------------------------------------
run_cat() {
  echo
  echo cat "$@"
  echo
  cat "$@"
}

# ----------------------------------------------------------------
announce() {
  echo
  echo "================================================================"
  echo
  echo "$@"
}

# ----------------------------------------------------------------
mention() {
  echo
  echo ---------------------------------------------------------------- "$@"
}

# ================================================================

echo ================================================================
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = 1; emit  @x } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = 1; emit  @x } '
echo ----------------------------------------------------------------
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = 1; emitp @x } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = 1; emitp @x } '
echo ----------------------------------------------------------------
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emit  @x } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emit  @x } '
echo ----------------------------------------------------------------
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emitp @x } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emitp @x } '

echo ================================================================
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = 1; emit  @* } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = 1; emit  @* } '
echo ----------------------------------------------------------------
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = 1; emitp @* } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = 1; emitp @* } '
echo ----------------------------------------------------------------
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emit  @* } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emit  @* } '
echo ----------------------------------------------------------------
path_to_mlr="../c/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emitp @* } '
path_to_mlr="../go/mlr"
run_mlr -n put 'end { @x = {"a":1, "b":2}; emitp @* } '

#echo ================================================================
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emit $*'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emit $*'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emit $a'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emit $a'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emit ${a}'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emit ${a}'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emit $["a"]'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emit $["a"]'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q '@a="foo"; emit @a'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q '@a="foo"; emit @a'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q '@a="foo"; emit @{a}'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q '@a="foo"; emit @{a}'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q '@a="foo"; emit @["a"]'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q '@a="foo"; emit @["a"]'
#
#echo ================================================================
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emitp $*'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emitp $*'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emitp $a'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emitp $a'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emitp ${a}'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emitp ${a}'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q 'emitp $["a"]'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q 'emitp $["a"]'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q '@a="foo"; emitp @a'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q '@a="foo"; emitp @a'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q '@a="foo"; emitp @{a}'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q '@a="foo"; emitp @{a}'
#
#echo ----------------------------------------------------------------
#path_to_mlr="../c/mlr"
#run_mlr --from r put -q '@a="foo"; emitp @["a"]'
#path_to_mlr="../go/mlr"
#run_mlr --from r put -q '@a="foo"; emitp @["a"]'


#path_to_mlr=../c/mlr
#run_mlr put -q '@t["u"] = $y; emit @*' ./reg-test/input/2.dkvp
#path_to_mlr=../go/mlr
#run_mlr put -q '@t["u"] = $y; emit @*' ./reg-test/input/2.dkvp
#path_to_mlr=../c/mlr
#run_mlr put -q '@t["u"] = $y; emitp @*' ./reg-test/input/2.dkvp
#path_to_mlr=../go/mlr
#run_mlr put -q '@t["u"] = $y; emitp @*' ./reg-test/input/2.dkvp

# ================================================================
