#!/bin/bash

path_to_mlr="./mlr"
indir="./reg-test/input"

build-go
if [ $? -ne 0 ]; then
  exit 1
fi

# ----------------------------------------------------------------
run_mlr() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
}

# ----------------------------------------------------------------
mlr_expect_fail() {
  echo
  echo $path_to_mlr "$@"
  echo
  $path_to_mlr "$@"
  status=$?
  if [ $status -eq 0 ]; then
    echo "failed to fail"
  fi
}

# ----------------------------------------------------------------
run_cat() {
  echo
  echo cat "$@"
  echo
  cat "$@"
}

# ----------------------------------------------------------------
announce() {
  echo
  echo "================================================================"
  echo
  echo "$@"
}

# ----------------------------------------------------------------
mention() {
  echo
  echo ---------------------------------------------------------------- "$@"
}

# ================================================================

for path_to_mlr in ../c/mlr ../go/mlr; do
  run_mlr --opprint --from $indir/medium.dkvp stats1 -a count,min,max -g a -f b,i,x
done

for path_to_mlr in ../c/mlr ../go/mlr; do
  run_mlr --oxtab --from $indir/medium.dkvp stats1 -a count,mode,antimode -f a,b
done

for path_to_mlr in ../c/mlr ../go/mlr; do
  run_mlr --oxtab --from $indir/medium.dkvp stats1 -a sum,count,mean,min,max -f i,x
done

#run_mlr --from $indir/medium.dkvp stats1 -a sum -f x
#run_mlr --from $indir/medium.dkvp stats1 -a count,sum -f i,x -g a,b

# ================================================================
