#!/bin/bash

set -euo pipefail

echo; mlr put -v '$y = 1 || 2' /dev/null
echo; mlr null put -v '$y = 1 || 2 || 3' /dev/null
echo; mlr null put -v '$y = 1 || 2 && 3' /dev/null
echo; mlr null put -v '$y = 1 && 2 || 3' /dev/null
echo; mlr null put -v '$y = 1 ? 2 : 3' /dev/null
echo; mlr null put -v '$y = $a + $b * $c' /dev/null
echo; mlr null put -v '$y = $a * $b * $c' /dev/null
echo; mlr null put -v '$y = $a ** $b ** $c' /dev/null
echo; mlr null put -v '$[2] = 3' /dev/null
echo; mlr null put -v '$[$y] = 4' /dev/null
#echo; mlr null put -v '${1} = 4' /dev/null
echo; mlr null put -v '$x = "abc"' /dev/null
echo; mlr null put -v '$["abc"] = "def"' /dev/null
echo; mlr null put -v '$[FILENAME] = FNR' /dev/null
echo; mlr null put -v '$x = $a + $b + $c' /dev/null
echo; mlr null put -v '$x = ($a + $b) + $c; $y = $a + ($b + $c); $z = $a + ($b)+ $c' /dev/null
echo; mlr null put -v '$x = 2 * $a + $b . $c' /dev/null
echo; mlr null put -v '$x = 2 * $a + ($b . $c)' /dev/null
echo; mlr null put -v '$x = (NF + NR) * 7; $y = OFS . $y . "hello"' /dev/null
echo; mlr null put -v '$x = 123. + 1e-2 / .2e3 + 1.e-3' /dev/null
