#!/bin/bash

wc -l \
  $(find pkg -name '*.go' | grep -v pkg/parsing) pkg/parsing/mlr.bnf \
| sort -n

echo
wc -c \
  $(find pkg -name '*.go' | grep -v pkg/parsing) pkg/parsing/mlr.bnf \
| sort -n \
| tail -n 5

