#!/bin/bash

ourdir=$(dirname $0)

mlrs="mlr5 ~/tmp/miller/mlr ./mlr"

echo; for mlr in $mlrs; do $ourdir/time-big-file csv     $mlr; done
echo; for mlr in $mlrs; do $ourdir/time-big-file csvlite $mlr; done
echo; for mlr in $mlrs; do $ourdir/time-big-file dkvp    $mlr; done
echo; for mlr in $mlrs; do $ourdir/time-big-file nidx    $mlr; done
echo; for mlr in $mlrs; do $ourdir/time-big-file xtab    $mlr; done
echo; for mlr in $mlrs; do $ourdir/time-big-file json    $mlr; done

