#ifndef JSON_ARRAY_INGEST_H
#define JSON_ARRAY_INGEST_H

typedef enum _json_array_ingest_t {
	JSON_ARRAY_INGEST_UNSPECIFIED,
	JSON_ARRAY_INGEST_FATAL,
	JSON_ARRAY_INGEST_SKIP,
	JSON_ARRAY_INGEST_AS_MAP,
} json_array_ingest_t;

#endif // JSON_ARRAY_INGEST_H
