#!/bin/bash

wc -l \
  $(find src/miller -name \*.go | grep -v src/miller/parsing) \
  src/miller/parsing/mlr.bnf \
| sort -n

echo
wc -c \
  $(find src/miller -name \*.go | grep -v src/miller/parsing) \
  src/miller/parsing/mlr.bnf \
| sort -n \
| tail -n 5

