#!/bin/bash

wc -l \
  $(find src -name \*.go | grep -v src/parsing) \
  src/parsing/mlr.bnf \
| sort -n

echo
wc -c \
  $(find src -name \*.go | grep -v src/parsing) \
  src/parsing/mlr.bnf \
| sort -n \
| tail -n 5

