name: miller
base: core24
version: git
summary: Miller is like awk, sed, cut, join and sort
description: |
  Miller is like awk, sed, cut, join, and sort for data formats such as CSV, TSV, JSON, JSON Lines, and positionally-indexed.

grade: stable
confinement: strict

adopt-info: miller

website: https://github.com/johnkerl/miller/issues
contact: https://github.com/johnkerl/miller/issues
issues: https://github.com/johnkerl/miller/issues
source-code: https://github.com/johnkerl/miller

license: BSD-2-Clause
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  s390x:
    build-on: [s390x]
    build-for: [s390x]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]

apps:
  miller:
    command: usr/local/bin/mlr
    plugs:
      - home

parts:
  miller:
    source: https://github.com/johnkerl/miller
    source-type: git
    plugin: make
    build-snaps:
      - go

    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
