// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(5), // md_token_field_name
			nil,      // md_token_assign
			nil,      // md_token_number
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // md_token_field_name
			nil,          // md_token_assign
			nil,          // md_token_number
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Body
			nil,       // md_token_field_name
			nil,       // md_token_assign
			nil,       // md_token_number
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: StatementBlock
			nil,       // md_token_field_name
			nil,       // md_token_assign
			nil,       // md_token_number
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // md_token_field_name
			shift(7), // md_token_assign
			nil,      // md_token_number
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // md_token_field_name
			reduce(4), // md_token_assign, reduce: FieldName
			nil,       // md_token_number
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // md_token_field_name
			nil,      // md_token_assign
			shift(9), // md_token_number
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // md_token_field_name
			nil,       // md_token_assign
			reduce(5), // md_token_number, reduce: Assign
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Statement
			nil,       // md_token_field_name
			nil,       // md_token_assign
			nil,       // md_token_number
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Number
			nil,       // md_token_field_name
			nil,       // md_token_assign
			nil,       // md_token_number
		},
	},
}
