/* Lexical elements */

_letter : 'a'-'z' | 'A'-'Z' ;

_digit : '0'-'9' ;

_idchar : _letter | _digit | '_' ;

id : (_letter | '_') {_idchar} ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

/* Syntax elements */

<< import "github.com/goccmack/gocc/example/errorrecovery/ast" >>

StmtList : 
      Stmt             << ast.NewStmtList($0) >>
    | StmtList Stmt    << ast.AppendStmt($0, $1) >>
;

Stmt : 
      id               << ast.NewStmt($0) >>
    | error
;