#!/bin/sh

for mlr in mlr5 mlr-go1.1*; do justtime $mlr --csv check ~/data/big.csv > /dev/null; done
echo

for mlr in mlr5 mlr-go1.1*; do justtime $mlr --csv cat ~/data/big.csv > /dev/null; done
echo

for mlr in mlr5 mlr-go1.1*; do justtime $mlr --csv --from ~/data/big.csv put -f ./scripts/chain-1.mlr > /dev/null; done
