#!/bin/sh

# https://go.dev/doc/manage-install

go install golang.org/dl/go1.18beta1@latest
go install golang.org/dl/go1.17.5@latest
go install golang.org/dl/go1.16.12@latest
go install golang.org/dl/go1.15.15@latest

go1.15.15   download
go1.16.12   download
go1.17.5    download
go1.18beta1 download
